apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: propensity-model-pvc
  namespace: model-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
