apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model-serving
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: fastapi
      port: 30000
      protocol: TCP
      targetPort: 30000
    - name: gradio
      port: 7860
      protocol: TCP
      targetPort: 7860
  type: NodePort