apiVersion: batch/v1
kind: Job
metadata:
  name: upload-model-job
  namespace: model-serving
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: fhe-model-sa
      containers:
        - name: model-uploader
          image: google/cloud-sdk:slim
          command:
            - /bin/sh
            - -c
            - |
              echo "Changing permissions..."
              chmod -R 777 /mnt/data
              echo "Uploading model to PVC from GCS..."
              gsutil -m cp -r gs://fhe-model-registry/model-checkpoints/* /mnt/data/
              echo "Uploading FHE models to PVC from GCS..."
              mkdir -p /mnt/data/fhe-models
              gsutil -m cp -r gs://fhe-model-registry/fhe-model-checkpoints/* /mnt/data/fhe-models/
              echo "Models uploaded successfully! Job complete."
          volumeMounts:
            - name: model-volume
              mountPath: /mnt/data
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: propensity-model-pvc
