version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: vominhtri1610/jenkins:2.541.2
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m -Dhudson.DNSMultiCast.disabled=true -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
